### ISSUE TITLE
Core Module TODO Tracker

### ISSUE THREAD

**Issue by newwby** [newwby/Godot-Prototyping-Framework#1]
# Documentation TODO

_Utilising Sphinx & ReadTheDocs, create a documentation system with appropriate makefiles so documentation is automatically pulled from gdscript files._

- [x] **Setup Sphinx/RTD connection**
- [x] **Document scripts**
  - [x] GlobalLog documentation
  - [x] DataUtility documentation
  - [x] NodeUtility documentation
  - [x] VariantUtility documentation
  - [ ] GlobalDebug documentation
- [ ] manually document scripts for future documentation updates

+ _**todo later**_
+ ~~DebugOverlayMenu documentation~~
+ ~~DebugCommandMenu documentation~~

# Desired Plugin Setting Features
- [ ] Editor dock for plugin settings
- [ ] Plugin settings stored in user folder

## Logger
- [ ] Logger autoload renameable in dock option (default to GlobalLog)
- [ ] Logger autoload toggle
- [ ] Logger utility so plugin scripts can use the autoload even if user doesn't want it

## Debug Menus
- [ ] Customisable action strings for debug overlay/command menu
- [ ] Debug overlay/command menu scene drag+drop (for easy user replacement)
- [ ] Autoload tracking debug overlay key/value pairs and

**Comment by newwby** [comment]
documentation handled through #2 
messy, need revising and an automatic solution in future; good first step would be to actually document the script files
